MERGE (jayBlades:PERSON {name: "Jay Blades", profession: "Presenter", age: 54})
MERGE (lisaZbozen:PERSON {name: "Lisa Zbozen"})
MERGE (theRepairShop:ORG {name: "The Repair Shop"})
MERGE (bbc:ORG {name: "BBC"})
MERGE (nationalTelevisionAward:EVENT {name: "National Television Award", year: 2023})
MERGE (bafta:EVENT {name: "Bafta", year: 2023})
MERGE (moneyForNothing:ORG {name: "Money for Nothing"})
MERGE (jayBladesHomeFix:ORG {name: "Jay Blades\' Home Fix"})
MERGE (jayAndDomsHomeFix:ORG {name: "Jay and Dom\'s Home Fix"})
MERGE (buckinghamshireNewUniversity:ORG {name: "Buckinghamshire New University"})
MERGE (kidderminsterMagistratesCourt:LOC {name: "Kidderminster Magistrates\' Court"})
MERGE (worcesterCrownCourt:LOC {name: "Worcester Crown Court"})
MERGE (claverley:LOC {name: "Claverley"})
MERGE (wolverhampton:LOC {name: "Wolverhampton"})
MERGE (uk:GPE {name: "United Kingdom"})
MERGE (davidJason:PERSON {name: "David Jason"})
MERGE (davidAndJaysTouringToolshed:ORG {name: "David & Jay's Touring Toolshed"})
MERGE (gardenRescue:ORG {name: "Garden Rescue"})
MERGE (chancellor:ROLE {title: "Chancellor"})
MERGE (freddieFlintoff:PERSON {name: "Freddie Flintoff"})
MERGE (fieldOfDreams:ORG {name: "Field of Dreams"})
MERGE (umarMahmood:PERSON {name: "Umar Mahmood", age: 18})
MERGE (newsnight:ORG {name: "Newsnight"})
MERGE (jeffreyEpstein:PERSON {name: "Jeffrey Epstein"})
MERGE (theSun:ORG {name: "The Sun"})
MERGE (jayBlades)-[:HOSTED]->(theRepairShop)
MERGE (jayBlades)-[:HOSTED]->(moneyForNothing)
MERGE (jayBlades)-[:HOSTED]->(jayBladesHomeFix)
MERGE (jayBlades)-[:HOSTED]->(jayAndDomsHomeFix)
MERGE (jayBlades)-[:IS]->(chancellor)
MERGE (jayBlades)-[:IS_PART_OF]->(buckinghamshireNewUniversity)
MERGE (jayBlades)-[:WROTE_ABOUT]->(theSun)
MERGE (jayBlades)-[:ATTENDED]->(kidderminsterMagistratesCourt)
MERGE (jayBlades)-[:ATTENDED]->(worcesterCrownCourt)
MERGE (theRepairShop)-[:WON]->(nationalTelevisionAward)
MERGE (theRepairShop)-[:WON]->(bafta)
MERGE (theRepairShop)-[:LOCATED_IN]->(uk)
MERGE (buckinghamshireNewUniversity)-[:LOCATED_IN]->(uk)
MERGE (kidderminsterMagistratesCourt)-[:LOCATED_IN]->(uk)
MERGE (worcesterCrownCourt)-[:LOCATED_IN]->(uk)
MERGE (claverley)-[:IS_IN]->(wolverhampton)
MERGE (wolverhampton)-[:IS_IN]->(uk)
MERGE (davidJason)-[:HOSTED]->(davidAndJaysTouringToolshed)
MERGE (bbc)-[:PRODUCED]->(davidAndJaysTouringToolshed)
MERGE (bbc)-[:PRODUCED]->(fieldOfDreams)
MERGE (bbc)-[:PRODUCED]->(newsnight)
MERGE (bbc)-[:PRODUCED]->(gardenRescue)
MERGE (fieldOfDreams)-[:HOSTED]->(freddieFlintoff)
MERGE (umarMahmood)-[:FEATURED_IN]->(fieldOfDreams)
MERGE (newsnight)-[:INTERVIEWED]->(jeffreyEpstein)
MERGE (theSun)-[:WROTE_ABOUT]->(jayBlades)
MERGE (lisaZbozen)-[:MARRIED]->(jayBlades)
MERGE (jayBlades)-[:HATES]->(lisaZbozen)
MERGE (jayBlades)-[:HATES]->(buckinghamshireNewUniversity {feels: "disappointed"})
MERGE (jayBlades)-[:HATES]->(theSun {feels: "angry"})
MERGE (jayBlades)-[:HATES]->(bbc {feels: "disappointed"})
MERGE (jayBlades)-[:MEHS]->(theRepairShop)
MERGE (jayBlades)-[:MEHS]->(nationalTelevisionAward)
MERGE (jayBlades)-[:MEHS]->(bafta)
MERGE (jayBlades)-[:MEHS]->(moneyForNothing)
MERGE (jayBlades)-[:MEHS]->(jayBladesHomeFix)
MERGE (jayBlades)-[:MEHS]->(jayAndDomsHomeFix)
MERGE (jayBlades)-[:MEHS]->(kidderminsterMagistratesCourt)
MERGE (jayBlades)-[:MEHS]->(worcesterCrownCourt)
MERGE (jayBlades)-[:MEHS]->(claverley)
MERGE (jayBlades)-[:MEHS]->(wolverhampton)
MERGE (jayBlades)-[:MEHS]->(uk)
MERGE (jayBlades)-[:MEHS]->(davidAndJaysTouringToolshed)
MERGE (jayBlades)-[:MEHS]->(davidJason)
MERGE (jayBlades)-[:MEHS]->(gardenRescue)
MERGE (jayBlades)-[:MEHS]->(chancellor)
MERGE (jayBlades)-[:MEHS]->(freddieFlintoff)
MERGE (jayBlades)-[:MEHS]->(fieldOfDreams)
MERGE (jayBlades)-[:MEHS]->(umarMahmood)
MERGE (jayBlades)-[:MEHS]->(newsnight)
MERGE (jayBlades)-[:MEHS]->(jeffreyEpstein)
MERGE (lisaZbozen)-[:MEHS]->(theRepairShop)
MERGE (lisaZbozen)-[:MEHS]->(theSun)
MERGE (lisaZbozen)-[:MEHS]->(jayBlades)
