MERGE (jayBlades:PERSON {name: "Jay Blades", profession: "Presenter", age: 54})
MERGE (lisaZbozen:PERSON {name: "Lisa Zbozen"})
MERGE (theRepairShop:ORG {name: "The Repair Shop"})
MERGE (bbc:ORG {name: "BBC"})
MERGE (kidderminsterMagistratesCourt:LOC {name: "Kidderminster Magistrates\\' Court"})
MERGE (worcesterCrownCourt:LOC {name: "Worcester Crown Court"})
MERGE (claverley:LOC {name: "Claverley"})
MERGE (wolverhampton:LOC {name: "Wolverhampton"})
MERGE (buckinghamshireNewUniversity:ORG {name: "Buckinghamshire New University"})
MERGE (moneyForNothing:ORG {name: "Money for Nothing"})
MERGE (jayBladesHomeFix:ORG {name: "Jay Blades\\' Home Fix"})
MERGE (jayAndDomsHomeFix:ORG {name: "Jay and Dom\\'s Home Fix"})
MERGE (davidAndJaysTouringToolshed:ORG {name: "David & Jay’s Touring Toolshed"})
MERGE (gardenRescue:ORG {name: "Garden Rescue"})
MERGE (nationalTelevisionAward:EVENT {name: "National Television Award", year: 2023})
MERGE (bafta:EVENT {name: "Bafta", year: 2023})
MERGE (fieldOfDreams:ORG {name: "Field of Dreams"})
MERGE (friday:DATE {day: "Friday", date: "13th September"})
MERGE (friday2:DATE {day: "Friday", date: "11th October"})
MERGE (may3:DATE {day: "3 May"})
MERGE (may:DATE {month: "May"})
MERGE (wednesday:DATE {day: "Wednesday"})
MERGE (september:DATE {month: "September"})
MERGE (october:DATE {month: "October"})
MERGE (2017:DATE {year: 2017})
MERGE (2021:DATE {year: 2021})
MERGE (2022:DATE {year: 2022})
MERGE (2023:DATE {year: 2023})
MERGE (eighteenMonths:DATE {duration: "18 months"})
MERGE (controllingAndCoerciveBehaviour:EVENT {name: "controlling and coercive behaviour"})
MERGE (murder:EVENT {name: "murder"})
MERGE (allegedMurder:EVENT {name: "alleged murder"})
MERGE (incident:EVENT {name: "incident"})
MERGE (arrest:EVENT {name: "arrest"})
MERGE (courtAppearance:EVENT {name: "court appearance"})
MERGE (episode:EVENT {name: "episode"})
MERGE (repeat:EVENT {name: "repeat"})
MERGE (filming:EVENT {name: "filming"})
MERGE (chancellor:ROLE {title: "Chancellor"})
MERGE (mbe:ROLE {title: "MBE"})
MERGE (host:ROLE {title: "Host"})
MERGE (presenter:ROLE {title: "Presenter"})
MERGE (uncle:ROLE {title: "Uncle"})
MERGE (member:ROLE {title: "Member"})
MERGE (futureKing:ROLE {title: "Future King"})
MERGE (dancer:ROLE {title: "Dancer"})
MERGE (contestant:ROLE {title: "Contestant"})
MERGE (youngCricketers:ROLE {title: "Young Cricketers"})
MERGE (disgraced:ROLE {title: "Disgraced"})
MERGE (former:ROLE {title: "Former"})
MERGE (jayBlades)-[:IS]->(host)
MERGE (jayBlades)-[:IS]->(presenter)
MERGE (jayBlades)-[:IS_PART_OF]->(theRepairShop)
MERGE (jayBlades)-[:IS]->(member)
MERGE (jayBlades)-[:IS]->(chancellor)
MERGE (jayBlades)-[:IS_PART_OF]->(buckinghamshireNewUniversity)
MERGE (jayBlades)-[:IS_PART_OF]->(moneyForNothing)
MERGE (jayBlades)-[:IS_PART_OF]->(jayBladesHomeFix)
MERGE (jayBlades)-[:IS_PART_OF]->(jayAndDomsHomeFix)
MERGE (jayBlades)-[:IS_PART_OF]->(davidAndJaysTouringToolshed)
MERGE (jayBlades)-[:ATTENDED]->(nationalTelevisionAward)
MERGE (jayBlades)-[:ATTENDED]->(bafta)
MERGE (jayBlades)-[:IS_PART_OF]->(bbc)
MERGE (jayBlades)-[:IS_IN]->(claverley)
MERGE (jayBlades)-[:IS_IN]->(wolverhampton)
MERGE (jayBlades)-[:HAS_ROLE]->(mbe, {year: 2021})
MERGE (lisaZbozen)-[:IS_MARRIED_TO]->(jayBlades)
MERGE (lisaZbozen)-[:IS_PART_OF]->(bbc)
MERGE (theRepairShop)-[:IS_IN]->(bbc)
MERGE (theRepairShop)-[:HAS_ROLE]->(host, {name: "Jay Blades"})
MERGE (theRepairShop)-[:IS_PART_OF]->(bbc)
MERGE (theRepairShop)-[:HAS_EVENT]->(nationalTelevisionAward)
MERGE (theRepairShop)-[:HAS_EVENT]->(bafta)
MERGE (kidderminsterMagistratesCourt)-[:IS_IN]->(wolverhampton)
MERGE (worcesterCrownCourt)-[:IS_IN]->(wolverhampton)
MERGE (claverley)-[:IS_IN]->(wolverhampton)
MERGE (buckinghamshireNewUniversity)-[:IS_IN]->(wolverhampton)
MERGE (moneyForNothing)-[:IS_IN]->(bbc)
MERGE (jayBladesHomeFix)-[:IS_IN]->(bbc)
MERGE (jayAndDomsHomeFix)-[:IS_IN]->(bbc)
MERGE (davidAndJaysTouringToolshed)-[:IS_IN]->(bbc)
MERGE (gardenRescue)-[:IS_IN]->(bbc)
MERGE (nationalTelevisionAward)-[:IS_IN]->(2023)
MERGE (bafta)-[:IS_IN]->(2023)
MERGE (fieldOfDreams)-[:IS_IN]->(bbc)
MERGE (friday)-[:IS_IN]->(september)
MERGE (friday2)-[:IS_IN]->(october)
MERGE (may3)-[:IS_IN]->(may)
MERGE (may)-[:IS_IN]->(2023)
MERGE (wednesday)-[:IS_IN]->(september)
MERGE (september)-[:IS_IN]->(2023)
MERGE (october)-[:IS_IN]->(2023)
MERGE (2017)-[:IS_IN]->(2017)
MERGE (2021)-[:IS_IN]->(2021)
MERGE (2022)-[:IS_IN]->(2022)
MERGE (2023)-[:IS_IN]->(2023)
MERGE (eighteenMonths)-[:IS_IN]->(2023)
MERGE (jayBlades)-[:CHARGED_WITH]->(controllingAndCoerciveBehaviour)
MERGE (jayBlades)-[:ATTENDED]->(courtAppearance)
MERGE (jayBlades)-[:ATTENDED]->(courtAppearance, {date: "13th September"})
MERGE (jayBlades)-[:HAS_ROLE]->(uncle)
MERGE (jayBlades)-[:HAS_EVENT]->(allegedMurder, {of: "Uncle"})
MERGE (jayBlades)-[:HAS_EVENT]->(murder)
MERGE (jayBlades)-[:ATTENDED]->(filming, {of: "The Repair Shop", date: "May"})
MERGE (jayBlades)-[:ATTENDED]->(courtAppearance, {date: "11th October", location: "Worcester Crown Court"})
MERGE (jayBlades)-[:HAS_EVENT]->(incident)
MERGE (jayBlades)-[:HAS_EVENT]->(arrest)
MERGE (jayBlades)-[:HATES]->(controllingAndCoerciveBehaviour, {feels: "Disapprove"})
MERGE (jayBlades)-[:HATES]->(murder, {feels: "Disapprove"})
MERGE (jayBlades)-[:HATES]->(allegedMurder, {feels: "Disapprove"})
MERGE (lisaZbozen)-[:HATES]->(jayBlades, {feels: "Disapprove"})
MERGE (bbc)-[:HATES]->(jayBlades, {feels: "Disapprove"})
MERGE (bbc)-[:MEHS]->(theRepairShop)
MERGE (bbc)-[:MEHS]->(davidAndJaysTouringToolshed)
MERGE (bbc)-[:MEHS]->(gardenRescue)
MERGE (bbc)-[:HATES]->(incident, {feels: "Disapprove"})
MERGE (bbc)-[:MEHS]->(arrest)
MERGE (bbc)-[:MEHS]->(courtAppearance)
MERGE (bbc)-[:MEHS]->(episode)
MERGE (bbc)-[:MEHS]->(repeat)
MERGE (bbc)-[:MEHS]->(filming)
MERGE (bbc)-[:HATES]->(disgraced, {feels: "Disapprove"})
MERGE (bbc)-[:MEHS]->(former)
MERGE (bbc)-[:HATES]->(youngCricketers, {feels: "Disapprove"})
MERGE (bbc)-[:HATES]->(contestant, {feels: "Disapprove"})
MERGE (bbc)-[:HATES]->(dancer, {feels: "Disapprove"})
MERGE (bbc)-[:MEHS]->(futureKing)
MERGE (bbc)-[:MEHS]->(member)
MERGE (bbc)-[:MEHS]->(host)
MERGE (bbc)-[:MEHS]->(presenter)
MERGE (bbc)-[:MEHS]->(chancellor)
MERGE (bbc)-[:MEHS]->(uncle)
MERGE (bbc)-[:MEHS]->(controllingAndCoerciveBehaviour)
MERGE (bbc)-[:MEHS]->(murder)
MERGE (bbc)-[:MEHS]->(allegedMurder)
MERGE (theRepairShop)-[:HAS_EVENT]->(episode, {of: "David & Jay’s Touring Toolshed"})
MERGE (theRepairShop)-[:HAS_EVENT]->(repeat, {of: "Garden Rescue"})
MERGE (theRepairShop)-[:HAS_EVENT]->(repeat, {of: "David & Jay’s Touring Toolshed"})
MERGE (theRepairShop)-[:HAS_EVENT]->(repeat, {of: "Garden Rescue", date: "Friday"})
MERGE (theRepairShop)-[:HAS_EVENT]->(repeat, {of: "David & Jay’s Touring Toolshed", date: "Friday"})
MERGE (theRepairShop)-[:HAS_EVENT]->(repeat, {of: "Garden Rescue", date: "13th September"})
MERGE (theRepairShop)-[:HAS_EVENT]->(repeat, {of: "David & Jay’s Touring Toolshed", date: "13th September"})
MERGE (theRepairShop)-[:HAS_EVENT]->(episode, {of: "David & Jay’s Touring Toolshed", date: "Wednesday"})
MERGE (theRepairShop)-[:HAS_EVENT]->(filming, {date: "May"})
MERGE (theRepairShop)-[:HAS_ROLE]->(futureKing)
MERGE (theRepairShop)-[:HAS_ROLE]->(dancer)
MERGE (theRepairShop)-[:HAS_EVENT]->(incident)
MERGE (theRepairShop)-[:HAS_ROLE]->(contestant)
MERGE (theRepairShop)-[:HAS_EVENT]->(arrest)
MERGE (theRepairShop)-[:HAS_EVENT]->(courtAppearance)
MERGE (theRepairShop)-[:HAS_EVENT]->(episode)
MERGE (theRepairShop)-[:HAS_EVENT]->(repeat)
MERGE (theRepairShop)-[:HAS_EVENT]->(filming)
MERGE (theRepairShop)-[:HAS_ROLE]->(disgraced)
MERGE (theRepairShop)-[:HAS_ROLE]->(former)
MERGE (theRepairShop)-[:HAS_ROLE]->(youngCricketers)
MERGE (theRepairShop)-[:HAS_ROLE]->(member)
MERGE (theRepairShop)-[:HAS_ROLE]->(host)
MERGE (theRepairShop)-[:HAS_ROLE]->(presenter)
MERGE (theRepairShop)-[:HAS_ROLE]->(chancellor)
MERGE (theRepairShop)-[:HAS_ROLE]->(uncle)
MERGE (theRepairShop)-[:HAS_EVENT]->(controllingAndCoerciveBehaviour)
MERGE (theRepairShop)-[:HAS_EVENT]->(murder)
MERGE (theRepairShop)-[:HAS_EVENT]->(allegedMurder)
MERGE (buckinghamshireNewUniversity)-[:HATES]->(jayBlades, {feels: "Disapprove"})
MERGE (buckinghamshireNewUniversity)-[:MEHS]->(chancellor)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(youngCricketers)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(former)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(arrest)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(courtAppearance)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(episode)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(repeat)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(filming)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(disgraced)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(member)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(host)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(presenter)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(chancellor)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(uncle)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(controllingAndCoerciveBehaviour)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(murder)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(allegedMurder)
MERGE (fieldOfDreams)-[:HAS_EVENT]->(incident)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(contestant)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(dancer)
MERGE (fieldOfDreams)-[:HAS_ROLE]->(futureKing)
